[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "busboy"]

[[redirects]]
  from = "/api/convert-webp-to-jpeg"
  to = "/.netlify/functions/convert-webp-to-jpeg"
  status = 200
